### PR TITLE
feat: use DBT_PROFILES_DIR env var as dbt profiles dir (if defined)

### LINKED ISSUE #255: dbt_sugar.core.exceptions.DbtProfileFileMissing: DBT_PROFILES_DIR env var is ignored
Having the dbt profiles directory configured in `DBT_PROFILES_DIR` environment variable and running `dbt-sugar audit` with the following sugar config results in `dbt_sugar.core.exceptions.DbtProfileFileMissing` error:

```yml
# sugar_config.yml
defaults:
  syrup: jaffle_shop
  target: dev
syrups:
  - name: jaffle_shop
    dbt_projects:
      - name: jaffle_shop
        path: .
```
It looks like `dbt-sugar` is looking for the profiles file only from `~/.dbt` directory.

dbt_sugar version: 0.0.0

### PR DESCRIPTION
**Pull request by smomni**
# Description

Implemented support for the `DBT_PROFILES_DIR` env var. If the variable is not defined, the profiles dir defaults to `~/.dbt`.

# How was the change tested

I manually checked that the profiles directory was resolved as `DBT_PROFILES_DIR` env var. Unfortunately, I didn't write any unit tests as the change seems trivial.

# Issue Information

Closes #255 

# Checklist

(Ideally, all boxes are checked by the time we merged the PR, if you don't know how to do any of these don't hesitate to say so in the PR and we'll help you out.)

- [x] I formatted my PR name according to [CONTRIBUTING.md](CONTRIBUTING.md)
- [x] I added a news fragment to help populating the changelog as encouraged in [CONTRIBUTING.md](CONTRIBUTING.md)
- [x] I added "Closes #<issue_number>" in the "Issue Information" section (if no issue, feel free to tick thick the box anyway).

### CODE REVIEW

**Comment by bastienboutonnet** [comment]
Thanks a lot for the PR @smomni 

As you say I think it's ok not to have a unit test on this as it's trivial and that line is kind of covered. I might write a test case for it at a later point though.

It looks like the CI is failing for a weird reason so I'm gonna take a quick looksie.

In the meantime would you mind writing a news fragment for our changelog? you can follow the instructions here to do that: https://github.com/bitpicky/dbt-sugar/blob/main/CONTRIBUTING.md#shout-out-your-hardwork-in-the-changelog

It's going to be a feature so the name of that news fragment file should be `256.feature.md`

**Comment by smomni** [comment]
@bastienboutonnet There's now a changelog entry :)

**Comment by bastienboutonnet** [comment]
Awesome! Thanks a lot for this. Strangely enough the CI passes locally so that's a bit strange.

I'm gonna to ahead and merge your branch. I'm planning to make a new alpha release soon, but we (long story) merged what looks like a regression on master so we'll want to fix that before we release.

I'll ping you in the issue when that is done if you want?

**Review by bastienboutonnet — APPROVED** [review]
Really nice work thanks @smomni

**Comment by smomni** [comment]
Thanks, this was probably the smallest contribution I've ever made 😄 Sure thing, ping me if there's anything!

**Comment by bastienboutonnet** [comment]
@smomni the new alpha build contains your changes: https://github.com/bitpicky/dbt-sugar/releases/tag/v0.1.0-a.3

Thanks a lot for the hard work and happy testing!

**Pull request merged**
